include:
  - board: seeeduino_xiao_ble
    shield: Enigma_04_kbd_L Enigma_04_kbd_L_O rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DKEYMAP_FILE=../../config/Enigma_04_OONISHI.keymap
    artifact-name: Enigma_04 OONISHI_L
    
  - board: seeeduino_xiao_ble
    shield: Enigma_04_kbd_R Enigma_04_kbd_R_O rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: Enigma_04 OONISHI_R

  - board: seeeduino_xiao_ble
    shield: Enigma_04_kbd_L Enigma_04_kbd_L_Q rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    cmake-args: -DKEYMAP_FILE=../../config/Enigma_04_QWERTY.keymap
    artifact-name: Enigma_04 QWERTY_L
    
  - board: seeeduino_xiao_ble
    shield: Enigma_04_kbd_R Enigma_04_kbd_R_Q rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: Enigma_04 QWERTY_R
    
  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: settings_reset
